### ISSUE TITLE
Communicate with the product and customer teams

### ISSUE THREAD

**Issue by drstm** [devops-orders/orders#7]
**As a** developer
**I need** to know the services my API will consume
**So that** I can design my API with their pre-requisites in mind

**Assumptions:**
* Product team has defined a set of API routes
* Customer team has defined a set of API routes

**Acceptance Criteria:**
```
Given our API definition
When it is called
Then external services can be seamlessly queried
```

**Comment by nivegan** [comment]
Product APIs:
* List
   * GET /products
* Read:
   * GET /products/<id>
* Create:
   * POST /products
* Update:
   * PUT /products/<id>
* Delete:
   * DELETE /products/<id>
* Query
   * GET /products?category=<category>
* Stock
   * PUT /products/<id>/buy

**Comment by nivegan** [comment]
For customers:
https://github.com/nyu-devops-fa19/customers/blob/master/README.md
